CREATE DATABASE SoftUni

CREATE TABLE Towns (
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(50) NOT NULL,
)

CREATE TABLE Addresses (
	Id INT PRIMARY KEY IDENTITY(1,1),
	AddressText NVARCHAR(70),
	TownId INT FOREIGN KEY REFERENCES Towns(Id) NOT NULL
)

CREATE TABLE Departments (
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(50) NOT NULL,
)

CREATE TABLE Employees (
	Id INT PRIMARY KEY IDENTITY(1,1),
	FirstName NVARCHAR(15) NOT NULL,
	MiddleName NVARCHAR(15),
	LastName NVARCHAR(15) NOT NULL,
	JobTitle NVARCHAR(15) NOT NULL,
	DepartmentId INT FOREIGN KEY REFERENCES Departments(Id) NOT NULL,
	HireDate DATETIME2 NOT NULL,
	Salary INT NOT NULL,
	AddressId INT FOREIGN KEY REFERENCES Addresses(Id) NOT NULL
)