CREATE TABLE Cities(
CityID INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Customers(
CustomerID INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50) NOT NULL,
Birthday DATE,
CityID INT FOREIGN KEY REFERENCES Cities(CityID) NOT NULL
)

CREATE TABLE Orders(
OrderID INT PRIMARY KEY IDENTITY,
CustomerID INT FOREIGN KEY REFERENCES Customers(CustomerID) 
)

CREATE TABLE ItemTypes(
ItemTypesID INT PRIMARY KEY IDENTITY(1, 1),
[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Items(
ItemID INT PRIMARY KEY IDENTITY(1, 1),
[Name] VARCHAR(50) NOT NULL,
ItemTypeID INT FOREIGN KEY REFERENCES ItemTypes (ItemTypesID) NOT NULL
)

CREATE TABLE OrderItems(
OrderID INT NOT NULL,
ItemID INT NOT NULL,
CONSTRAINT PK_OrderItem PRIMARY KEY (OrderID, ItemID),
CONSTRAINT FK_Order FOREIGN KEY (OrderID) REFERENCES Orders (OrderID),
CONSTRAINT FK_Item FOREIGN KEY (ItemID) REFERENCES Items (ItemID)
)